BUILD_WORKFLOW=build-image-and-push-using-docksock-wf.json

get_pods:
	/bin/kubectl get pods -n default

do_build:
	@cat $(BUILD_WORKFLOW) | sed \
		-e 's/%MODEL_VERSION%/$(MODEL_VERSION)/' \
		-e "s/%GITHUB_USER%/${GITHUB_USER}/" \
		-e "s/%GITHUB_TOKEN%/${GITHUB_TOKEN}/" | /bin/kubectl -n default create -f -

